version: "3.5"

services:
  lumen:
    ports:
      - "8000:8000"
    volumes:
      - /home/docker/registro/html:/var/www/html
    build: .
    command: php -S lumen:8000 -t public
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/docker/registro/mysql:/var/lib/mysql:rw
volumes:
  mysql-data:
